spring:
  application:
    name:
      apigateway
  cloud:
    gateway:
      routes:
        - id: Employee2
          uri: lb://employee2
          predicates:
            - Path= /employee2/search-by-employee-id/**
            - Path= /employee2/search-by-employee-email/**
          filters:
            - name: RequestRateLimiter
              arg:
                requestedTokens: 3
                replenishRate: 10
                burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
        - id: Employee
          uri: lb://employee
          predicates:
            - Path= /employee/**
          filters:
            - name: RequestRateLimiter
              arg:
                requestedTokens: 3
                replenishRate: 10
                burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
        - id: Employee
          uri: lb://employee
          predicates:
            - Path= /employee/search-by-employee-email/**
            - RemoteAddr= 127.0.0.1/24
          filters:
            - name: RequestRateLimiter
              arg:
                requestedTokens: 3
                replenishRate: 10
                burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: mypass
      timeout: 60000

  main:
    web-application-type:
      reactive
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
      example:
        apigateway:
          ConfigGateway: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

###DockerRedis


###






